
package appaprendercomplete;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author SaraZarama
 */
public class frmTest1 extends javax.swing.JFrame {

    ButtonGroup respuesta1 = new ButtonGroup();
    ButtonGroup respuesta2 = new ButtonGroup();
    ButtonGroup respuesta3 = new ButtonGroup();
    ButtonGroup respuesta4 = new ButtonGroup();
    ButtonGroup respuesta5 = new ButtonGroup();
    ButtonGroup respuesta6 = new ButtonGroup();
    ButtonGroup respuesta7 = new ButtonGroup();
    
    
    public frmTest1() {
        initComponents();
        
        respuesta1.add(rbtA1);
        respuesta1.add(rbtV1);
        respuesta1.add(rbtK1);
        
        respuesta2.add(rbtA2);
        respuesta2.add(rbtV2);
        respuesta2.add(rbtK2);
        
        respuesta3.add(rbtA3);
        respuesta3.add(rbtV3);
        respuesta3.add(rbtK3);
        
        respuesta4.add(rbtA4);
        respuesta4.add(rbtV4);
        respuesta4.add(rbtK4);
        
        respuesta5.add(rbtA5);
        respuesta5.add(rbtV5);
        respuesta5.add(rbtK5);
        
        respuesta6.add(rbtA6);
        respuesta6.add(rbtV6);
        respuesta6.add(rbtK6);
        
        respuesta7.add(rbtA7);
        respuesta7.add(rbtV7);
        respuesta7.add(rbtK7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rbtA1 = new javax.swing.JRadioButton();
        rbtK1 = new javax.swing.JRadioButton();
        rbtV1 = new javax.swing.JRadioButton();
        rbtA2 = new javax.swing.JRadioButton();
        rbtK2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbtV2 = new javax.swing.JRadioButton();
        rbtK3 = new javax.swing.JRadioButton();
        rbtV3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtA3 = new javax.swing.JRadioButton();
        rbtV4 = new javax.swing.JRadioButton();
        rbtA4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbtK4 = new javax.swing.JRadioButton();
        rbtV5 = new javax.swing.JRadioButton();
        rbtA5 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbtK5 = new javax.swing.JRadioButton();
        rbtK6 = new javax.swing.JRadioButton();
        rbtV6 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbtA6 = new javax.swing.JRadioButton();
        rbtK7 = new javax.swing.JRadioButton();
        rbtA7 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rbtV7 = new javax.swing.JRadioButton();
        btnRespuesta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPadres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        jLabel1.setText("Cual de las siguientes actividades disfrutas más?");

        rbtA1.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtA1.setText("Escuchar música ");

        rbtK1.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtK1.setText("Bailar con buena música ");

        rbtV1.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtV1.setText("Ver películas");

        rbtA2.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtA2.setText("Noticias del mundo");

        rbtK2.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtK2.setText("Cómico y de entretenimiento");

        jLabel2.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        jLabel2.setText("¿Qué programa de televisión prefieres? ");

        rbtV2.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtV2.setText("Reportajes de descubrimientos y lugares");

        rbtK3.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtK3.setText("Tiendes a tocarla");

        rbtV3.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtV3.setText("La observas");

        jLabel3.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        jLabel3.setText("Cuando conversas con otra persona, tú: ");

        rbtA3.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtA3.setText("La escuchas atentamente ");

        rbtV4.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtV4.setText("Un televisor");

        rbtA4.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtA4.setText("Un estéreo");

        jLabel4.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        jLabel4.setText("Cuál prefieres?");

        rbtK4.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtK4.setText("Un jacuzzi");

        rbtV5.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtV5.setText("Ir al cine ");

        rbtA5.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtA5.setText("Ir a un concierto ");

        jLabel5.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        jLabel5.setText("¿Qué prefieres hacer un sábado por la tarde? ");

        rbtK5.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtK5.setText(" Quedarte en casa");

        rbtK6.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtK6.setText("Examen de opción múltiple ");

        rbtV6.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtV6.setText("Examen escrito");

        jLabel6.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        jLabel6.setText("¿Qué tipo de exámenes se te facilitan más?");

        rbtA6.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtA6.setText("Examen oral");

        rbtK7.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtK7.setText("A través de la intuición ");

        rbtA7.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtA7.setText("Pidiendo indicaciones ");

        jLabel7.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        jLabel7.setText(" ¿Cómo te orientas más fácilmente? ");

        rbtV7.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        rbtV7.setText("Mediante el uso de un mapa");

        btnRespuesta.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        btnRespuesta.setText("Qué tipo de aprendizaje tengo?");
        btnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        jButton1.setText("Actividades");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPadres.setFont(new java.awt.Font("Ambit SemiBold", 0, 12)); // NOI18N
        btnPadres.setText("Espacio para padres");
        btnPadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtV7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtA7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtK7, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtA6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtV6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtK6, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtK5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtA5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtV5, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtK4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtA4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtV4, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtV3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtK3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtK2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtA2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtK1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPadres, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtK1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtV2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtK2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtA2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtA3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtV3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtK3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtK4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtA4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtV4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtK5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtA5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtV5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtA6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtV6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtK6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtV7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtA7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtK7)
                .addGap(26, 26, 26)
                .addComponent(btnRespuesta)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnPadres))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaActionPerformed
        // suma de puntos para obtener el resultado:
        
        int contadorA = 0;
        int contadorV = 0;
        int contadorK = 0;
        
        if(rbtA1.isSelected())
        {
            contadorA = contadorA +1;
            
        } else if(rbtV1.isSelected()) {
            contadorV = contadorV +1;
        } else {
            if(rbtK1.isSelected())
            {
                contadorK = contadorK+1;
            }
        }
        
        if(rbtA2.isSelected())
        {
            contadorA = contadorA +1;
            
        } else if(rbtV2.isSelected()) {
            contadorV = contadorV +1;
        } else {
            if(rbtK2.isSelected())
            {
                contadorK = contadorK+1;
            }
        }
        
        if(rbtA3.isSelected())
        {
            contadorA = contadorA +1;
            
        } else if(rbtV3.isSelected()) {
            contadorV = contadorV +1;
        } else {
            if(rbtK3.isSelected())
            {
                contadorK = contadorK+1;
            }
        }
        
        if(rbtA4.isSelected())
        {
            contadorA = contadorA +1;
            
        } else if(rbtV4.isSelected()) {
            contadorV = contadorV +1;
        } else {
            if(rbtK4.isSelected())
            {
                contadorK = contadorK+1;
            }
        }
        
        if(rbtA5.isSelected())
        {
            contadorA = contadorA +1;
            
        } else if(rbtV5.isSelected()) {
            contadorV = contadorV +1;
        } else {
            if(rbtK5.isSelected())
            {
                contadorK = contadorK+1;
            }
        }
        
        if(rbtA6.isSelected())
        {
            contadorA = contadorA +1;
            
        } else if(rbtV6.isSelected()) {
            contadorV = contadorV +1;
        } else {
            if(rbtK6.isSelected())
            {
                contadorK = contadorK+1;
            }
        }
        
        if(rbtA7.isSelected())
        {
            contadorA = contadorA +1;
            
        } else if(rbtV7.isSelected()) {
            contadorV = contadorV +1;
        } else {
            if(rbtK7.isSelected())
            {
                contadorK = contadorK+1;
            }
        }
        
        if(contadorA>contadorV || contadorA>contadorK)
        {
            JOptionPane.showMessageDialog(this, "Tu estilo de aprendizaje es mayormente Auditivo");
        } else if(contadorV>contadorA || contadorV>contadorK)
        {
            JOptionPane.showMessageDialog(this, "Tu estilo de aprendizaje es mayormente Visual");
        } else {
            JOptionPane.showMessageDialog(this, "Tu estilo de aprendizaje es mayormente Kinestésico");
        }
        
    }//GEN-LAST:event_btnRespuestaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // retorno a actividades.
            
        frmActividadesV ventana = new frmActividadesV();
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadresActionPerformed
        // Para llevar al espacio de padres
        
        frmPadresFAQ ventana = new frmPadresFAQ();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPadresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTest1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPadres;
    private javax.swing.JButton btnRespuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rbtA1;
    private javax.swing.JRadioButton rbtA2;
    private javax.swing.JRadioButton rbtA3;
    private javax.swing.JRadioButton rbtA4;
    private javax.swing.JRadioButton rbtA5;
    private javax.swing.JRadioButton rbtA6;
    private javax.swing.JRadioButton rbtA7;
    private javax.swing.JRadioButton rbtK1;
    private javax.swing.JRadioButton rbtK2;
    private javax.swing.JRadioButton rbtK3;
    private javax.swing.JRadioButton rbtK4;
    private javax.swing.JRadioButton rbtK5;
    private javax.swing.JRadioButton rbtK6;
    private javax.swing.JRadioButton rbtK7;
    private javax.swing.JRadioButton rbtV1;
    private javax.swing.JRadioButton rbtV2;
    private javax.swing.JRadioButton rbtV3;
    private javax.swing.JRadioButton rbtV4;
    private javax.swing.JRadioButton rbtV5;
    private javax.swing.JRadioButton rbtV6;
    private javax.swing.JRadioButton rbtV7;
    // End of variables declaration//GEN-END:variables
}
